version: 1.0
jobs:
  build:
    steps:
      - name: Install dependencies
        command: npm install
      - name: Build app
        command: npm run build
      - name: Start JSON server
        command: json-server --watch db.json --port $PORT
        background: true
